language: c
compiler:
    - gcc
addons:
  apt:
    packages:
      - &base_deps
        - libxinerama-dev
        - libxft-dev
        - libx11-dev
        - libxrender-dev

script:
    - make clean
    - make

